version: '3.8'
services:
  rexa-bot:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - rexa-bot:latest
    image: rexa-bot:latest
    container_name: rexa-bot
    env_file: .env
    restart: unless-stopped